### ISSUE TITLE
Update Pre-Commit Hooks

### ISSUE THREAD

**Issue by yoonspark** [TillRS/SUN_TopicModel#7]
Based on the current state of the repo, I recommend the following updates for pre-commit hooks.

1. Update `.pre-commit-config.yaml` as follows:

    ```yaml
    repos:
      - repo: https://github.com/astral-sh/ruff-pre-commit
        rev: v0.3.0
        hooks:
          - id: ruff
            args: ["--fix"]
          - id: ruff-format
      - repo: https://github.com/pre-commit/mirrors-mypy
        rev: v1.7.0
        hooks:
          - id: mypy
            args: ["--ignore-missing-imports"]
    ```

2. Update `.github/workflows/ci.yml` as follows:

    ```yaml
    [...]
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install .'[test]'
          - name: Cache pre-commit hooks
            uses: actions/cache@v2
            with:
              path: ~/.cache/pre-commit
              key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
          - name: Install pre-commit
            run: pip install pre-commit
          - name: Run pre-commit
            run: pre-commit run --all-files
          - name: Run tests
            run: pytest
    ```
